### ISSUE TITLE
Make this a template repo

### ISSUE THREAD

**Issue by bsoyka** [fatih-yavuz/my-links#13]
This could be a [template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) so people can copy it without forking.

**Comment by fatih-yavuz** [comment]
Would you like to create one and add it to the README? @bsoyka

**Comment by bsoyka** [comment]
@fatih-yavuz: I could, but I just meant you could go into the settings on this repo and update that setting.

**Comment by fatih-yavuz** [comment]
It is a template repo atm but It can be forked @bsoyka I will deal with this some other time. It is not something urgent

**Comment by bsoyka** [comment]
That's perfect actually, exactly what I was going for.
